version: '3'

services:

  ticket-postgres:
    container_name: ticket-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: alierfan
      POSTGRES_USER: postgres
    ports:
      - 5433:5432
    volumes:
    - ticket-pgdata:/var/lib/postgresql/data
    - ./express-ticket-server/CSV_Data:/var/lib/postgresql/data/CSV_Data/

  auth-postgres:
    container_name: auth-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: alierfan
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
    - auth-pgdata:/var/lib/postgresql/data
    
  
  webbackend-redis:
    container_name: webbackend-redis
    image: redis
    ports:
      - 6379:6379
  
  bank:
    container_name: bank
    build: ./Bank
    ports:
      - 8050:8000
    tty: true

  auth-server:
    container_name: auth-server 
    build: ./go-auth-server
    depends_on:
      - ticket-postgres
      - auth-postgres
      - webbackend-redis
    environment:
      - DB_HOST=auth-postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_DATABASE=postgres
      - DB_PASSWORD=alierfan
      - REDIS_HOST=http://redis:6379
    ports:
      - 3000:3000
    
  
  ticket-server:
    container_name: ticket-server
    build: ./express-ticket-server
    restart: always
    depends_on:
      - ticket-postgres
    environment:
      - DB_HOST=ticket-postgres
      - DB_USER=postgres
      - DB_DATABASE=postgres
      - DB_PASSWORD=alierfan
      - BANK_HOST=http://bank:8000
      - GO_AUTH_HOST=http://auth-server:3000
    ports:
      - 3001:3001

  flight-backend-nginx:
    container_name: flight-backend-nginx
    image: nginx:alpine
    restart: always
    ports:
      - 9050:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

   
volumes:
  ticket-pgdata:
    driver: local
  auth-pgdata:
    driver: local